/*
 * File: app/store/Departments.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PDMSWebView.store.Departments', {
    extend: 'Ext.data.Store',

    requires: [
        'PDMSWebView.model.Department'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'PDMSWebView.model.Department',
            storeId: 'DepartmentsStore',
            proxy: {
                type: 'ajax',
                url: 'http://localhost/PDMSwebservices/departments.asmx/GetDepartments',
                reader: {
                    type: 'xml',
                    idProperty: '',
                    root: 'root',
                    record: 'Department'
                }
            }
        }, cfg)]);
    }
});