/*
 * File: app/store/TherapeuticGroup.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PDMSWebView.store.TherapeuticGroup', {
    extend: 'Ext.data.Store',

    requires: [
        'PDMSWebView.model.TherapeuticGroup'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'PDMSWebView.model.TherapeuticGroup',
            storeId: 'MyArrayStore',
            proxy: {
                type: 'ajax',
                url: 'http://localhost:8080/databases/test/docs/',
                reader: {
                    type: 'array'
                }
            }
        }, cfg)]);
    }
});