/*
 * File: app/view/DepartmentList.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PDMSWebView.view.DepartmentList', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.departments',

    width: 150,
    title: 'List',
    forceFit: true,
    store: 'Departments',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 164,
                    dataIndex: 'Name',
                    text: 'Department'
                }
            ]
        });

        me.callParent(arguments);
    }

});