/*
 * File: app/view/DrugRepository.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PDMSWebView.view.DrugRepository', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.drugrepository',

    itemId: 'drugrepository',
    width: 600,
    collapsed: false,
    collapsible: false,
    title: 'Drug Repository',
    enableColumnHide: false,
    enableColumnMove: false,
    rowLines: true,
    store: 'DrugRepository',
    rootVisible: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {
                itemId: 'drugrepositoryview',
                plugins: [
                    Ext.create('Ext.tree.plugin.TreeViewDragDrop', {
                        ddGroup: 'ddPrescription',
                        displayField: 'Name',
                        dragText: 'prescribe drug',
                        enableDrop: false
                    })
                ]
            },
            columns: [
                {
                    xtype: 'treecolumn',
                    width: 475,
                    dataIndex: 'Name',
                    text: 'Groups',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    defaultWidth: 150,
                    dataIndex: 'Route',
                    text: 'Route'
                }
            ],
            selModel: Ext.create('Ext.selection.RowModel', {
                mode: 'SINGLE'
            })
        });

        me.callParent(arguments);
    }

});