/*
 * File: app/view/DrugRepository.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PDMSWebView.view.DrugRepository', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.drugrepository',

    itemId: 'drugrepository',
    width: 600,
    collapsed: true,
    collapsible: false,
    title: 'Drug Repository',
    store: 'DrugRepository',
    rootVisible: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {

            },
            columns: [
                {
                    xtype: 'treecolumn',
                    dataIndex: 'text',
                    text: 'Nodes',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'value',
                    text: 'Value'
                }
            ]
        });

        me.callParent(arguments);
    }

});