/*
 * File: app/view/Orders.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PDMSWebView.view.Orders', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.orders',

    requires: [
        'PDMSWebView.view.override.Orders'
    ],

    title: 'Orders',
    store: 'Orders',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'numbercolumn',
                    width: 60,
                    dataIndex: 'Number',
                    text: 'No',
                    format: '0,000'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Type',
                    groupable: true,
                    text: 'Type'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'StartDateTime',
                    text: 'Start'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'StopDateTime',
                    text: 'Stop'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Prescriber',
                    text: 'Prescriber'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Text',
                    text: 'Text',
                    flex: 1
                },
                {
                    xtype: 'booleancolumn',
                    width: 80,
                    dataIndex: 'Active',
                    text: 'Active'
                }
            ],
            selModel: Ext.create('Ext.selection.CheckboxModel', {

            }),
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'cycle',
                            itemId: 'cycleActiveOrders',
                            width: 100,
                            showText: true,
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'Active'
                                    },
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'Inactive'
                                    },
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'All'
                                    }
                                ]
                            }
                        }
                    ]
                }
            ],
            features: [
                {
                    ftype: 'grouping'
                }
            ]
        });

        me.callParent(arguments);
    }

});