/*
 * File: app/view/PatientRecord.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PDMSWebView.view.PatientRecord', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.patientrecord',

    requires: [
        'PDMSWebView.view.Orders'
    ],

    title: 'Patient Record',
    activeTab: 0,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'orders'
                },
                {
                    xtype: 'panel',
                    layout: {
                        type: 'border'
                    },
                    title: 'Medication Orders',
                    items: [
                        {
                            xtype: 'form',
                            flex: 1,
                            region: 'center',
                            layout: {
                                columns: 3,
                                type: 'table'
                            },
                            bodyPadding: 10,
                            title: 'Prescription',
                            items: [
                                {
                                    xtype: 'fieldcontainer',
                                    rowspan: 2,
                                    height: 240,
                                    padding: '',
                                    width: 400,
                                    fieldLabel: '',
                                    labelWidth: 0,
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            padding: 10,
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            title: 'Generic',
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    fieldLabel: 'Substance',
                                                    labelAlign: 'top'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    flex: 1,
                                                    width: 40,
                                                    fieldLabel: 'Quantity',
                                                    labelAlign: 'top',
                                                    labelSeparator: ' '
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    fieldLabel: 'Unit',
                                                    labelAlign: 'top',
                                                    labelSeparator: ' '
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldset',
                                            padding: 10,
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            title: 'Generic',
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    fieldLabel: 'Substance',
                                                    labelAlign: 'top'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    flex: 1,
                                                    width: 40,
                                                    fieldLabel: 'Quantity',
                                                    labelAlign: 'top',
                                                    labelSeparator: ' '
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    fieldLabel: 'Unit',
                                                    labelAlign: 'top',
                                                    labelSeparator: ' '
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    rowspan: 2,
                                    height: 120,
                                    width: 400,
                                    fieldLabel: 'Solution'
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    rowspan: 2,
                                    height: 120,
                                    width: 400,
                                    fieldLabel: 'Patient'
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    height: 120,
                                    width: 400,
                                    fieldLabel: 'Frequency'
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    height: 120,
                                    width: 400,
                                    fieldLabel: 'Duration'
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    height: 120,
                                    width: 400,
                                    fieldLabel: 'Options'
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    height: 120,
                                    width: 400,
                                    fieldLabel: 'Dose'
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    height: 120,
                                    width: 400,
                                    fieldLabel: 'Total'
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    height: 120,
                                    width: 400,
                                    fieldLabel: 'Rate'
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    colspan: 2,
                                    height: 120,
                                    width: 800,
                                    fieldLabel: 'Text'
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    height: 120,
                                    width: 400,
                                    fieldLabel: 'Start Stop'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'orders',
                            dock: 'bottom',
                            height: 400,
                            collapsed: true,
                            collapsible: true
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});