/*
 * File: app/view/PatientRecord.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PDMSWebView.view.PatientRecord', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.patientrecord',

    requires: [
        'PDMSWebView.view.Orders'
    ],

    title: 'Patient Record',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'orders'
                }
            ]
        });

        me.callParent(arguments);
    }

});