/*
 * File: app/view/PatientList.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PDMSWebView.view.PatientList', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.patientlist',

    title: 'Patients',
    store: 'Patients',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'numbercolumn',
                    width: 60,
                    dataIndex: 'Number',
                    text: 'No',
                    format: '0,000'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'BedId',
                    text: 'Bed Id'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'HospitalNumber',
                    text: 'Hosp No'
                },
                {
                    xtype: 'gridcolumn',
                    width: 150,
                    dataIndex: 'LastName',
                    text: 'Last Name'
                },
                {
                    xtype: 'gridcolumn',
                    width: 150,
                    dataIndex: 'FirstName',
                    text: 'First Name'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'BirthDate',
                    text: 'Birth Date'
                },
                {
                    xtype: 'numbercolumn',
                    width: 50,
                    dataIndex: 'Age',
                    text: 'Age',
                    format: '0,000'
                },
                {
                    xtype: 'numbercolumn',
                    width: 50,
                    dataIndex: 'Weight',
                    text: 'Weight',
                    format: '0,000'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'AdmissionDate',
                    text: 'Admission Date'
                },
                {
                    xtype: 'gridcolumn',
                    width: 150,
                    dataIndex: 'MainSpecialism',
                    text: 'Specialism'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Physician',
                    text: 'Physician'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'AdmissionDiagonosis',
                    text: 'Diagnosis',
                    flex: 1
                }
            ]
        });

        me.callParent(arguments);
    }

});