/*
 * File: app/view/Prescription.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PDMSWebView.view.Prescription', {
    extend: 'Ext.form.Panel',
    alias: 'widget.prescriptionform',

    layout: {
        columns: 3,
        type: 'table'
    },
    bodyPadding: 15,
    title: 'Prescription',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldcontainer',
                    height: 200,
                    padding: '',
                    width: 400,
                    fieldLabel: '',
                    labelWidth: 0,
                    items: [
                        {
                            xtype: 'fieldset',
                            padding: 10,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            title: 'Generic',
                            items: [
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    fieldLabel: 'Substance',
                                    labelAlign: 'top'
                                },
                                {
                                    xtype: 'numberfield',
                                    width: 100,
                                    fieldLabel: 'Quantity',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                },
                                {
                                    xtype: 'combobox',
                                    width: 100,
                                    fieldLabel: 'Unit',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            padding: 10,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            title: 'Shape and Route',
                            items: [
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    fieldLabel: 'Shape',
                                    labelAlign: 'top'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    fieldLabel: 'Route',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    height: 200,
                    padding: '',
                    width: 400,
                    fieldLabel: '',
                    labelWidth: 0,
                    items: [
                        {
                            xtype: 'fieldset',
                            padding: 10,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            title: 'Solution',
                            items: [
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    fieldLabel: 'Substance',
                                    labelAlign: 'top'
                                },
                                {
                                    xtype: 'numberfield',
                                    width: 100,
                                    fieldLabel: 'Quantity',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                },
                                {
                                    xtype: 'combobox',
                                    width: 100,
                                    fieldLabel: 'Unit',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            padding: 10,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            title: 'Concentration',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    flex: 1,
                                    fieldLabel: 'Concentration',
                                    labelAlign: 'top'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    fieldLabel: 'Unit',
                                    labelAlign: 'top'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    fieldLabel: 'Unit',
                                    labelAlign: 'top'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    height: 200,
                    padding: '',
                    width: 400,
                    fieldLabel: '',
                    labelWidth: 0,
                    items: [
                        {
                            xtype: 'fieldset',
                            padding: 10,
                            layout: {
                                type: 'column'
                            },
                            title: 'Weight',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    width: 100,
                                    fieldLabel: 'Quantity',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                },
                                {
                                    xtype: 'combobox',
                                    width: 100,
                                    fieldLabel: 'Unit',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            padding: 10,
                            layout: {
                                type: 'column'
                            },
                            title: 'Height',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    width: 100,
                                    fieldLabel: 'Quantity',
                                    labelAlign: 'top'
                                },
                                {
                                    xtype: 'combobox',
                                    width: 100,
                                    fieldLabel: 'Unit',
                                    labelAlign: 'top'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    height: 100,
                    width: 400,
                    layout: {
                        type: 'fit'
                    },
                    fieldLabel: 'Frequency',
                    hideLabel: true,
                    items: [
                        {
                            xtype: 'fieldset',
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            title: 'Frequency',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    width: 100,
                                    fieldLabel: 'Quantity',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                },
                                {
                                    xtype: 'combobox',
                                    width: 100,
                                    fieldLabel: 'Unit',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    height: 100,
                    width: 400,
                    layout: {
                        type: 'fit'
                    },
                    fieldLabel: 'Duration',
                    hideLabel: true,
                    items: [
                        {
                            xtype: 'fieldset',
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            title: 'Duration',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    width: 100,
                                    fieldLabel: 'Quantity',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                },
                                {
                                    xtype: 'combobox',
                                    width: 100,
                                    fieldLabel: 'Unit',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    height: 100,
                    width: 400,
                    layout: {
                        type: 'fit'
                    },
                    fieldLabel: 'Options',
                    hideLabel: true,
                    labelWidth: 50,
                    items: [
                        {
                            xtype: 'fieldset',
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            title: 'Options',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    flex: 1,
                                    padding: 10,
                                    fieldLabel: 'Continuous',
                                    labelAlign: 'top'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    flex: 1,
                                    padding: 10,
                                    fieldLabel: 'Solution',
                                    labelAlign: 'top'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    flex: 1,
                                    padding: 10,
                                    fieldLabel: 'Duration',
                                    labelAlign: 'top'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    flex: 1,
                                    padding: 10,
                                    fieldLabel: 'PRN',
                                    labelAlign: 'top'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    rowspan: 2,
                    height: 200,
                    padding: '',
                    width: 400,
                    fieldLabel: '',
                    labelWidth: 0,
                    items: [
                        {
                            xtype: 'fieldset',
                            padding: 10,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            title: 'Dose',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    width: 100,
                                    fieldLabel: 'Quantity',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                },
                                {
                                    xtype: 'combobox',
                                    width: 100,
                                    fieldLabel: 'Unit',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                },
                                {
                                    xtype: 'combobox',
                                    width: 70,
                                    fieldLabel: 'Adjust',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            padding: 10,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            title: 'Dose Administer',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    width: 100,
                                    fieldLabel: 'Quantity',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                },
                                {
                                    xtype: 'combobox',
                                    width: 100,
                                    fieldLabel: 'Unit',
                                    labelAlign: 'top'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    rowspan: 2,
                    height: 200,
                    padding: '',
                    width: 400,
                    fieldLabel: '',
                    labelWidth: 0,
                    items: [
                        {
                            xtype: 'fieldset',
                            padding: 10,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            title: 'Total',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    width: 100,
                                    fieldLabel: 'Quantity',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                },
                                {
                                    xtype: 'combobox',
                                    width: 100,
                                    fieldLabel: 'Unit',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                },
                                {
                                    xtype: 'combobox',
                                    width: 70,
                                    fieldLabel: 'Adjust',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                },
                                {
                                    xtype: 'combobox',
                                    width: 100,
                                    fieldLabel: 'Unit',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            padding: 10,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            title: 'Total Administer',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    width: 100,
                                    fieldLabel: 'Quantity',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                },
                                {
                                    xtype: 'combobox',
                                    width: 100,
                                    fieldLabel: 'Unit',
                                    labelAlign: 'top'
                                },
                                {
                                    xtype: 'combobox',
                                    width: 100,
                                    fieldLabel: 'Unit',
                                    labelAlign: 'top'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    rowspan: 2,
                    height: 200,
                    padding: '',
                    width: 400,
                    fieldLabel: '',
                    labelWidth: 0,
                    items: [
                        {
                            xtype: 'fieldset',
                            padding: 10,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            title: 'Rate',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    width: 100,
                                    fieldLabel: 'Quantity',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                },
                                {
                                    xtype: 'combobox',
                                    width: 100,
                                    fieldLabel: 'Unit',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                },
                                {
                                    xtype: 'combobox',
                                    width: 70,
                                    fieldLabel: 'Adjust',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                },
                                {
                                    xtype: 'combobox',
                                    width: 100,
                                    fieldLabel: 'Unit',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            padding: 10,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            title: 'Rate Administer',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    width: 100,
                                    fieldLabel: 'Quantity',
                                    labelAlign: 'top',
                                    labelSeparator: ' '
                                },
                                {
                                    xtype: 'combobox',
                                    width: 100,
                                    fieldLabel: 'Unit',
                                    labelAlign: 'top'
                                },
                                {
                                    xtype: 'combobox',
                                    width: 100,
                                    fieldLabel: 'Unit',
                                    labelAlign: 'top'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    colspan: 2,
                    height: 120,
                    padding: 10,
                    width: 700,
                    layout: {
                        type: 'fit'
                    },
                    fieldLabel: 'Label',
                    hideLabel: true,
                    items: [
                        {
                            xtype: 'fieldset',
                            padding: 10,
                            layout: {
                                type: 'fit'
                            },
                            title: 'Prescription Text',
                            items: [
                                {
                                    xtype: 'textareafield',
                                    fieldLabel: 'Label',
                                    hideLabel: true
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    colspan: 1,
                    height: 120,
                    width: 400,
                    fieldLabel: 'Label',
                    hideLabel: true,
                    items: [
                        {
                            xtype: 'fieldset',
                            padding: 10,
                            title: 'Start Stop Date Time',
                            items: [
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    fieldLabel: 'Start'
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    fieldLabel: 'Stop'
                                }
                            ]
                        }
                    ]
                }
            ],
            listeners: {
                afterlayout: {
                    fn: me.onFormAfterLayout,
                    single: true,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onFormAfterLayout: function(container, layout, eOpts) {
        var formPanel =  container;
        var dropTargetEl = formPanel.body.dom;

        console.log(dropTargetEl);

        formPanel.dropTarget = new Ext.dd.DropTarget(dropTargetEl, {
            ddGroup     : 'ddPrescription',
            notifyEnter : function(ddSource, e, data) {

                //Add some flare to invite drop.
                //formPanel.body.stopFx();
                formPanel.body.highlight();
            },
            notifyDrop  : function(ddSource, e, data){

                console.log(data.records[0]);

                Ext.Msg.alert('going to prescribe: ' + data.records[0].data.Name);
                // Reference the record (single selection) for readability
                //var selectedRecord = ddSource.dragData.selections[0];


                // Load the record into the form
                //formPanel.getForm().loadRecord(selectedRecord);


                // Delete record from the grid.  not really required.
                //ddSource.grid.store.remove(selectedRecord);

                return(true);
            }
        });
    }

});