/*
 * File: app/view/ThemePicker.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PDMSWebView.view.ThemePicker', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.themepicker',

    fieldLabel: 'Theme',
    labelWidth: 60,
    displayField: 'name',
    store: 'Themes',
    valueField: 'url',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});