/*
 * File: app/controller/Medication.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PDMSWebView.controller.Medication', {
    extend: 'Ext.app.Controller',

    views: [
        'PediatricFormularyText'
    ],

    onGridpanelViewReady: function(tablepanel, eOpts) {
        var store = Ext.StoreMgr.get('TherapeuticGroup');

        store.proxy.url = PDMSWebView.app.createUrl(store.proxy.url, PDMSWebView.RavenDB);
        store.load();
    },

    onDrugrepositoryItemDblClick: function(dataview, record, item, index, e, eOpts) {
        console.log(record.data.id);
        if (record.data.id.length == 7) {
            PDMSWebView.model.PediatricFormularyText.load({query:'ATC:' + record.data.id}, { success: this.showPediatricFormularyText });
        }

    },

    onViewNodeDragOver: function(targetNode, position, dragData, e, eOpts) {
        Ext.Msg.alert('Going to prescribe ', index);
    },

    showPediatricFormularyText: function(text) {
        console.log(text);
        PDMSWebView.view.PediatricFormularyText.create({html:text.data.Html}).show();
    },

    init: function(application) {
        this.control({
            "gridpanel": {
                viewready: this.onGridpanelViewReady
            },
            "treepanel": {
                itemdblclick: this.onDrugrepositoryItemDblClick,
                nodedragover: this.onViewNodeDragOver
            }
        });
    }

});
