/*
 * File: app/controller/Orders.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PDMSWebView.controller.Orders', {
    extend: 'Ext.app.Controller',

    onCycleChange: function(cycle, item, eOpts) {
        var patient = this.getController('Patients').getCurrentPatient();

        if (patient) {
            this.loadOrders(patient.HospitalNumber);
        }
    },

    loadOrders: function(hospNum) {
        var active = Ext.ComponentQuery.query('#cycleActiveOrders')[0].getActiveItem().text;

        Ext.StoreMgr.get('Orders').load({params:{hospitalNumber: hospNum, active: active}});
    },

    init: function(application) {
        this.control({
            "cycle": {
                change: this.onCycleChange
            }
        });
    }

});
