/*
 * File: app/controller/Patients.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PDMSWebView.controller.Patients', {
    extend: 'Ext.app.Controller',

    onGridpanelItemClick: function(dataview, record, item, index, e, eOpts) {
        this.setCurrentPatient(record.data);

        this.getController('DetailsPanel').setDetails('patientrecord');
        this.getController('Orders').loadOrders(this.getCurrentPatient().HospitalNumber, 'Active');

    },

    setCurrentPatient: function(patient) {
        this.currentPatient = patient;
    },

    getCurrentPatient: function() {
        return this.currentPatient;
    },

    init: function(application) {
        this.control({
            "#patientinfolist": {
                itemclick: this.onGridpanelItemClick
            }
        });
    }

});
