/*
 * File: app/model/PatientInfo.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PDMSWebView.model.PatientInfo', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'ID'
        },
        {
            name: 'Number'
        },
        {
            name: 'HospitalNumber'
        },
        {
            name: 'LastName'
        },
        {
            name: 'FirstName'
        },
        {
            name: 'BirthDate'
        },
        {
            name: 'AdmissionDate'
        },
        {
            name: 'Age'
        },
        {
            name: 'MainSpecialism'
        },
        {
            name: 'AdmissionDiagonosis'
        },
        {
            name: 'Physician'
        },
        {
            name: 'BedId'
        },
        {
            name: 'Weight'
        },
        {
            name: 'Department'
        }
    ]
});