/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'Department',
        'PatientInfo',
        'Order',
        'TreeRecord',
        'ATCItem',
        'PediatricFormularyText',
        'Unit',
        'Prescription',
        'Shape',
        'QuantityUnit'
    ],
    stores: [
        'Departments',
        'DepartmentTree',
        'Themes',
        'Patients',
        'Orders',
        'DrugRepository',
        'TherapeuticGroup',
        'Product',
        'Unit',
        'Generic',
        'Shape',
        'Route',
        'QuantityUnit'
    ],
    views: [
        'PDMSWebView',
        'DepartmentTree',
        'DepartmentList',
        'DepartmentTabPanel',
        'ThemePicker',
        'DetailPanel',
        'PatientList',
        'PatientRecord',
        'Orders',
        'DrugRepository',
        'TherapeuticGroupList',
        'PediatricFormularyText',
        'Prescription',
        'QuantityUnit'
    ],
    autoCreateViewport: true,
    controllers: [
        'Departments',
        'Themes',
        'Tools',
        'Patients',
        'DetailsPanel',
        'Orders',
        'Medication',
        'ApplicationManagement'
    ],
    name: 'PDMSWebView',

    launch: function() {
        Ext.Ajax.cors = true;
        Ext.Ajax.useDefaultXhrHeader = false;
        Ext.Ajax.useDefaultHeader = false;
        Ext.Ajax.disableCaching = false;

        PDMSWebView.RavenDB = "http://" + document.location.host + ":8080/";


    },

    createUrl: function(origUrl, host) {
        return host + origUrl.split('/').splice(3).join('/');
    },

    fullScreen: function() {
        var element = Ext.ComponentQuery.query('viewport')[0].getEl().dom;

        // These function will not exist in the browsers that don't support fullscreen mode yet, 
        // so we'll have to check to see if they're available before calling them.

        if (element.mozRequestFullScreen) {
            // This is how to go into fullscren mode in Firefox
            // Note the "moz" prefix, which is short for Mozilla.
            //element.mozRequestFullScreen();
        } else if (element.webkitRequestFullScreen) {
            // This is how to go into fullscreen mode in Chrome and Safari
            // Both of those browsers are based on the Webkit project, hence the same prefix.
            //element.webkitRequestFullScreen();
        }
        // Hooray, now we're in fullscreen mode!

    }

});
